# ================== APP ==================
spring.application.name=EvenTAura

# ================== PROFILE ==================
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# ================== COMMON ==================
spring.jpa.properties.hibernate.format_sql=true

app.secret-key=${APP_SECRET_KEY}

server.port=${PORT:8080}