spring.config.activate.on-profile=prod

# ================== DATABASE ==================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ================== JPA ==================
spring.jpa.hibernate.ddl-auto=${DDL_AUTO}
spring.jpa.show-sql=false

# ================== SECURITY ==================
spring.security.user.name=${ADMIN_USERNAME}
spring.security.user.password=${ADMIN_PASSWORD}

# ================== OAUTH ==================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

# ================== IMAGE STORAGE ==================
cloudinary.cloud_name=${IMAGE_CLOUD_NAME}
cloudinary.api_key=${IMAGE_CLOUD_API_KEY}
cloudinary.api_secret=${IMAGE_CLOUD_SECRET}