spring:
  config:
    activate:
      on-profile: prod

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-3.5-flash

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}

    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email,profile

  mail:
    host: smtp.resend.com
    port: 587
    username: resend
    password: ${RESEND_API_KEY}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  base-url: ${BASE_URL}

  cookie:
    secure: ${COOKIE_SECURE}
    same-site: ${COOKIE_SITE}

  mail:
    from: ${EMAIL_FROM}

cloudinary:
  cloud_name: ${IMAGE_CLOUD_NAME}
  api_key: ${IMAGE_CLOUD_API_KEY}
  api_secret: ${IMAGE_CLOUD_SECRET}

springdoc:
  api-docs:
    enabled: ${API_DOC}
  swagger-ui:
    enabled: ${SWAGGER_UI}