spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.reactive.ReactiveUserDetailsServiceAutoConfiguration,org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration

# ================== APP ==================
spring.application.name=EvenTAura

# ================== PROFILE ==================
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# ================== COMMON ==================
spring.jpa.properties.hibernate.format_sql=true

app.secret-key=${APP_SECRET_KEY}

server.port=${PORT:8080}

# ================== ACCESS TOKEN EXPIRY TIME ==================
jwt.access.expiration=${ACCESS_EXPIRY}

# ================== REFRESH TOKEN EXPIRY TIME ==================
jwt.refresh.expiration=${REFRESH_EXPIRY}