name: CampusHive CI

on:
  push:
    branches:
      - main

jobs:
  campushive-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'termium'
          java-version: '21'

      - name: Build
        run: mvn clean package
