name: Sonar

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Give execute permission
        run: chmod +x mvnw

      - name: Build and analyze
        run: ./mvnw clean install -DskipTests org.sonarsource.scanner.maven:sonar-maven-plugin:3.10.0.2594:sonar -Dsonar.projectKey=Anuj-code-AI_Event-Management-System -Dsonar.organization=anuj-code-ai -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}




